app/routes.php
<?php

/*
  |--------------------------------------------------------------------------
  | Application Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register all of the routes for an application.
  | It's a breeze. Simply tell Laravel the URIs it should respond to
  | and give it the Closure to execute when that URI is requested.
  |
 */




Route::resource('blog', 'BlogController');
Route::match(array('GET', 'POST'), '/',function (){
    return Redirect::to('blog');
});

app/views/layout/footer.blade.php
<footer class="blog-footer">
    <p>Blog template built for <a href="http://getbootstrap.com">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
    <p>
        <a href="#">Back to top</a>
    </p>
</footer>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
{{ HTML::script('js/bootstrap.min.js') }}
{{ HTML::script('js/docs.min.js') }}
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
{{ HTML::script('js/ie10-viewport-bug-workaround.js') }}

app/views/layout/head.blade.php
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Blog Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    {{ HTML::style('css/bootstrap.min.css') }}

    <!-- Custom styles for this template -->
    {{ HTML::style('css/blog.css') }}

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    {{ HTML::script('js/ie-emulation-modes-warning.js') }}

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

app/views/layout/headpost.blade.php
<a href="{{URL::route('blog.edit',$post->url)}}" ><span class="glyphicon glyphicon-edit" aria-hidden="true"></span></a>
    {{HTML::linkRoute('blog.show',$post->title,$post->url,array('class'=>'h1') )}} 
<p class="lead blog-description">
    {{$post->subTitle}}
</p>
<p class="blog-post-meta">
    <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
    {{$post->getDateCreated_at()}} by <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
    <a href="#">{{$post->user->name}}</a>
</p>

app/views/layout/master.blade.php
<!DOCTYPE html>
<html lang="es">

    @include('layout/head')

    <body>
        @include('layout/nav')

        <div class="container">

            <div class="blog-header">
                <h1 class="blog-title">{{$blog->title}}</h1>
                <p class="lead blog-description">{{$blog->subTitle}}</p>
            </div>
            @if(Session::has('message'))
            <div class="alert {{Session::get('alert')}} alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <strong>Srocha!</strong> {{ Session::get('message') }}
            </div>
            @endif
            
            @section('conntet')
                No found
            @show

            @include('layout/footer')

    </body>


</html>

app/views/layout/nav.blade.php
<div class="blog-masthead">
    <div class="container">
        <nav class="blog-nav">
            {{HTML::linkRoute('blog.index','Home',array(),array('class'=>'blog-nav-item'))}}
            {{HTML::linkRoute('blog.create','New Post',array(),array('class'=>'blog-nav-item'))}}
        </nav>
    </div>
</div>

app/views/layout/sidebar.blade.php
<div class="col-sm-3 col-sm-offset-1 blog-sidebar">
    <div class="sidebar-module sidebar-module-inset">
        <h4>About</h4>
        <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
    </div>
    <div class="sidebar-module">
        <h4>Archives</h4>
        <ol class="list-unstyled">
            <li><a href="#">March 2014</a></li>
            <li><a href="#">February 2014</a></li>
            <li><a href="#">January 2014</a></li>
            <li><a href="#">December 2013</a></li>
            <li><a href="#">November 2013</a></li>
            <li><a href="#">October 2013</a></li>
            <li><a href="#">September 2013</a></li>
            <li><a href="#">August 2013</a></li>
            <li><a href="#">July 2013</a></li>
            <li><a href="#">June 2013</a></li>
            <li><a href="#">May 2013</a></li>
            <li><a href="#">April 2013</a></li>
        </ol>
    </div>
    <div class="sidebar-module">
        <h4>Elsewhere</h4>
        <ol class="list-unstyled">
            <li><a href="#">GitHub</a></li>
            <li><a href="#">Twitter</a></li>
            <li><a href="#">Facebook</a></li>
        </ol>
    </div>
</div><!-- /.blog-sidebar -->

app/views/layout/tagspost.blade.php
<span class="glyphicon glyphicon-tags" aria-hidden="true"></span> Tags: 
@foreach ($post->tags as $tag)
    <a href="#">{{$tag->name}}</a>
@endforeach